version: 0.2

env:
  secrets-manager:
    SERVERLESS_ACCESS_KEY: "serverless/access-key2"

dashboard: false 

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install -g serverless

  pre_build:
    commands:
      - echo Running pre-build commands...
      # - if [ -z "$SERVERLESS_ACCESS_KEY" ]; then echo "SERVERLESS_ACCESS_KEY is missing!"; exit 1; fi
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo "Checking if SERVERLESS_ACCESS_KEY is set"
      - export SERVERLESS_ACCESS_KEY=AKCfVBAY931wlN2xy8kBESGdspVPrNnVOF6Bxy3N1NH7L
      - echo $SERVERLESS_ACCESS_KEY
      - serverless deploy --verbose --debug

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Running post-build commands...

artifacts:
  files:
    - '**/*'
  discard-paths: yes