# "service" is the name of this project. This will also be added to your AWS resource names.
org: davidcher86

service: sls-second-dev
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
